from django.db import models
from uuid import uuid4

from .utils import model_error_messages


class Reaction(models.Model):
    """
    Reaction model with fields of ``uuid``, ``reaction_count``, ``emoji``,
    ``glizzy``, ``created_at``, and ``updated_at``.

    The ``uuid`` field is autogenerated during creation.

    The ``emoji`` field has a foreign key of the Emoji model.

    The ``glizzy`` field has a foreign key of the Emoji model.

    The ``created_at`` field is autogenerated during creation and only once.

    The ``updated_at`` field is autogenerated during creation and subsequently
    when the model is changed.
    """

    uuid = models.UUIDField(
        unique=True,
        default=uuid4,
        editable=False,
        error_messages=model_error_messages["uuid"],
    )
    reaction_count = models.IntegerField(
        default=0, error_messages=model_error_messages["reaction_count"]
    )
    emoji = models.ForeignKey(
        "emoji.Emoji",
        related_name="reactions",
        on_delete=models.CASCADE,
        error_messages=model_error_messages["emoji"],
    )
    glizzy = models.ForeignKey(
        "glizzy.Glizzy",
        related_name="reactions",
        on_delete=models.CASCADE,
        error_messages=model_error_messages["glizzy"],
    )
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return f"{self.reaction_count} {self.emoji} on {self.glizzy}"

    class Meta:
        verbose_name = "Reaction"
