# Generated by Django 4.0.6 on 2022-07-12 20:15

from django.db import migrations, models
import glizzy.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Glizzy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "blank": "The name cannot be empty.",
                            "max_length": "The name should be no more than 100 characters.",
                            "required": "The name is required.",
                            "unique": "The name already exists.",
                        },
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        error_messages={
                            "max_length": "The slug should be no more than 100 characters."
                        },
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "short_info",
                    models.CharField(
                        error_messages={
                            "blank": "The short info cannot be empty.",
                            "max_length": "The short info should be no more than 200 characters.",
                            "required": "The short info is required.",
                        },
                        max_length=200,
                    ),
                ),
                (
                    "long_info",
                    models.TextField(
                        error_messages={
                            "blank": "The long info cannot be empty.",
                            "required": "The long info is required.",
                        }
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        error_messages={
                            "blank": "The image cannot be empty.",
                            "required": "The image is required.",
                        },
                        upload_to=glizzy.utils.upload_glizzy_image_to,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Glizzy",
            },
        ),
    ]
