# Generated by Django 4.0.6 on 2022-07-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glizzy", "0002_glizzy_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glizzy",
            name="long_info",
            field=models.TextField(
                error_messages={
                    "blank": "The long info cannot be empty.",
                    "invalid": "Invalid value for the long info.",
                    "null": "The long info cannot be empty.",
                    "required": "The long info is required.",
                }
            ),
        ),
        migrations.AlterField(
            model_name="glizzy",
            name="name",
            field=models.CharField(
                error_messages={
                    "blank": "The name cannot be empty.",
                    "invalid": "Invalid value for the name.",
                    "max_length": "The name should be no more than 100 characters.",
                    "null": "The name cannot be empty.",
                    "required": "The name is required.",
                    "unique": "The name already exists.",
                },
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="glizzy",
            name="short_info",
            field=models.CharField(
                error_messages={
                    "blank": "The short info cannot be empty.",
                    "invalid": "Invalid value for the short info.",
                    "max_length": "The short info should be no more than 200 characters.",
                    "null": "The short info cannot be empty.",
                    "required": "The short info is required.",
                },
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="glizzy",
            name="slug",
            field=models.SlugField(
                blank=True,
                error_messages={
                    "does_not_exist": "The slug does not exist.",
                    "invalid": "Invalid value for the slug.",
                    "max_length": "The slug should be no more than 100 characters.",
                    "null": "The slug cannot be empty.",
                },
                max_length=100,
                null=True,
            ),
        ),
    ]
