from django.db import models


class Glizzy(models.Model):
    """
    Glizzy model with fields of ``name``, ``slug``, ``short_info``,
    ``long_info``, ``image``, ``created_at``, and ``updated_at``.

    The ``slug`` field is autogenerated during the pre_save signal.

    The ``created_at`` field is autogenerated during creation and only once.

    The ``updated_at`` field is autogenerated during creation and subsequently when the
    model is changed.
    """

    name = models.CharField(
        max_length=100,
        unique=True,
        error_messages={
            "blank": "The name cannot be empty.",
            "max_length": "The name should be no more than 100 characters.",
            "required": "The name is required.",
            "unique": "The name already exists.",
        },
    )
    slug = models.SlugField(
        max_length=100,
        null=True,
        blank=True,
        error_messages={
            "max_length": "The slug should be no more than 100 characters.",
        },
    )
    short_info = models.CharField(
        max_length=200,
        error_messages={
            "blank": "The short info cannot be empty.",
            "max_length": "The short info should be no more than 200 characters.",
            "required": "The short info is required.",
        },
    )
    long_info = models.TextField(
        error_messages={
            "blank": "The long info cannot be empty.",
            "required": "The long info is required.",
        }
    )
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Glizzy"
