# Generated by Django 4.0.6 on 2022-07-18 20:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("glizzy", "0003_alter_glizzy_long_info_alter_glizzy_name_and_more"),
        ("emoji", "0002_alter_emoji_emoji_alter_emoji_name_alter_emoji_slug"),
        ("reaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="emoji",
            field=models.ForeignKey(
                error_messages={
                    "blank": "The emoji cannot be empty.",
                    "does_not_exist": "The emoji does not exist.",
                    "invalid": "Invalid value for the emoji.",
                    "null": "The emoji cannot be empty.",
                    "required": "The emoji is required.",
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="emoji.emoji",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="glizzy",
            field=models.ForeignKey(
                error_messages={
                    "blank": "The glizzy cannot be empty.",
                    "does_not_exist": "The glizzy does not exist.",
                    "invalid": "Invalid value for the glizzy.",
                    "null": "The glizzy cannot be empty.",
                    "required": "The glizzy is required.",
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="glizzy.glizzy",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction_count",
            field=models.IntegerField(
                default=0,
                error_messages={
                    "blank": "The reaction count cannot be empty.",
                    "invalid": "The reaction count needs to be a valid integer.",
                    "min_value": "The reaction count should be 0 or greater.",
                    "required": "The reaction count is required.",
                },
                validators=[
                    django.core.validators.MinValueValidator(limit_value=0)
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                error_messages={"unique": "The uuid is not unique."},
                unique=True,
            ),
        ),
    ]
