from django.db import models
from uuid import uuid4

from .utils import model_error_messages


class Emoji(models.Model):
    """
    Emoji model with fields of ``uuid``, ``emoji``, ``name``, ``slug``,
    ``created_at``, and ``updated_at``.

    The ``uuid`` field is autogenerated during creation.

    The ``slug`` field is autogenerated during the pre_save signal.

    The ``created_at`` field is autogenerated during creation and only once.

    The ``updated_at`` field is autogenerated during creation and subsequently
    when the model is changed.
    """

    uuid = models.UUIDField(
        unique=True,
        default=uuid4,
        editable=False,
        error_messages=model_error_messages["uuid"],
    )
    emoji = models.CharField(
        max_length=1, unique=True, error_messages=model_error_messages["emoji"]
    )
    name = models.CharField(
        max_length=100,
        unique=True,
        error_messages=model_error_messages["name"],
    )
    slug = models.SlugField(
        max_length=100,
        null=True,
        blank=True,
        error_messages=model_error_messages["slug"],
    )
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.emoji

    class Meta:
        verbose_name = "Emoji"
