# Generated by Django 4.0.6 on 2022-07-14 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emoji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        error_messages={"unique": "The uuid is not unique."},
                        unique=True,
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        error_messages={
                            "blank": "The emoji cannot be empty.",
                            "max_length": "The emoji should be no more than 1 character.",
                            "required": "The emoji is required.",
                            "unique": "The emoji already exists.",
                        },
                        max_length=1,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "blank": "The name cannot be empty.",
                            "max_length": "The name should be no more than 100 characters.",
                            "required": "The name is required.",
                            "unique": "The name already exists.",
                        },
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        error_messages={
                            "max_length": "The slug should be no more than 100 characters."
                        },
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Emoji",
            },
        ),
    ]
