# Generated by Django 4.0.6 on 2022-07-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emoji", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emoji",
            name="emoji",
            field=models.CharField(
                error_messages={
                    "blank": "The emoji cannot be empty.",
                    "does_not_exist": "The emoji does not exist.",
                    "invalid": "Invalid value for the emoji.",
                    "max_length": "The emoji should be no more than 1 character.",
                    "null": "The emoji cannot be empty.",
                    "required": "The emoji is required.",
                    "unique": "The emoji already exists.",
                },
                max_length=1,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="emoji",
            name="name",
            field=models.CharField(
                error_messages={
                    "blank": "The name cannot be empty.",
                    "invalid": "Invalid value for the name.",
                    "max_length": "The name should be no more than 100 characters.",
                    "null": "The name cannot be empty.",
                    "required": "The name is required.",
                    "unique": "The name already exists.",
                },
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="emoji",
            name="slug",
            field=models.SlugField(
                blank=True,
                error_messages={
                    "does_not_exist": "The slug does not exist.",
                    "invalid": "Invalid value for the slug.",
                    "max_length": "The slug should be no more than 100 characters.",
                    "null": "The slug cannot be empty.",
                },
                max_length=100,
                null=True,
            ),
        ),
    ]
